root = "."
tmp_dir = "tmp"

[build]
include_ext = ["go", "tmpl"]
exclude_dir = ["./tmp"]
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = true
kill_delay = 500 # ms

[log]
time = false

[misc]
clean_on_exit = true
